<div class="product-view-ancillary-links">
  
  <div class="narrower-wrapper">
    <a href="/your-delivery" title="Delivery"><img src="<?php echo $block->getViewFileUrl('Rcreek_ProductViewWoodSamples::images/delivery-v3.jpg'); ?>" /></a>
    <a href="/wood-samples" title="Wood Samples"><img src="<?php echo $block->getViewFileUrl('Rcreek_ProductViewWoodSamples::images/product_view_wood_samples-v2.jpg'); ?>" /></a>
  </div>
</div>
