<?php  
use Magento\Framework\View\TemplateEngine\Php as TE; /** @var TE $this */
use WeltPixel\OwlCarouselSlider\Block\Slider\Custom as B; /** @var B $block */ $b = $block; /** @var B $b */
$cfg  = $b->getSliderConfiguration();
/**
 * 2020-01-17 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * 1) "Defer offscreen images for the `WeltPixel_OwlCarouselSlider` module":
 * https://github.com/tradefurniturecompany/site/issues/152
 * 2) The `lazyLoad` feature does not have an UI backend setting for an unknown reason,
 * so the feature can be enabled only programmatically.
 */
$cfgG = ['lazyLoad' => 1] + $cfg['slider_config'];
if (dfa($cfgG, 'status')) {
	$sliderId = (int)$b['slider_id']; /** @var int $sliderId */
	$breakpoint = $b->getBreakpointConfiguration();
	$bnConfig = $cfg['banner_config'];
	$cfg = json_encode($cfgG);
	$mediaUrl = $b->getMediaUrl();
	$isGatEnabled = $b->isGatEnabled();
	if ($cfgG['show_title'] && trim($cfgG['title'])) { ?>
		<div class='content-heading'>
			<h2 class='title'><?= $cfgG['title']; ?></h2>
		</div>
	<?php } ?>
	<div class='custom-slider'>
		<div class='owl-carousel-custom-<?= $sliderId;?>'>
			<?php
			foreach ($bnConfig as $bn) { /** @var array(string => string) $bn */
				$url = dfa($bn, 'url'); /** @var string $url */
				$target = dfa($bn, 'target', '_blank'); /** @var string $target */
				$bnType = (int)dfa($bn, 'banner_type'); /** @var int $bnType */
				$buttonText = dfa($bn, 'button_text'); /** @var string $buttonText */
				$gaPromoId = dfa($bn, 'ga_promo_id'); /** @var string $gaPromoId */
				$gaPromoName = dfa($bn, 'ga_promo_name'); /** @var string $gaPromoId */
				$gaPromoCreative = dfa($bn, 'ga_promo_creative'); /** @var string $gaPromoCreative */
				$gaPromoPosition = dfa($bn, 'ga_promo_position'); /** @var string $gaPromoPosition */
				?>
					<div class="banner-item banner-<?= $bn['id']; ?>">
						<?php if ($bnType == 1) : ?>
							<?php if (!$buttonText): ?>
								<?php if (isset($url)): ?>
									<a
										href="<?= $url; ?>"
										target="<?= $target; ?>"
										<?php if($isGatEnabled):?>
											data-track-promo-id="<?= $gaPromoId; ?>"
											data-track-promo-name="<?= $gaPromoName; ?>"
											data-track-promo-creative="<?= $gaPromoCreative; ?>"
											data-track-promo-position="<?= $gaPromoPosition; ?>"
										<?php endif;?>
									>
								<?php endif; ?>
							<?php endif; ?>
							<span class="banner-image">
								<?php
									$image = $mediaUrl . dfa($bn, 'image');
									$altText = dfa($bn, 'alt_text'); /** @var string $altText */
									echo df_tag('img', ['alt' => $altText, 'title' => $altText] + (!$cfgG['lazyLoad']
										? ['src' => $image]
										: ['class' => 'owl-lazy', 'data-src' => $image, 'data-src-retina' => $image]
									));
								?>
							</span>
							<?php if (!$buttonText): ?>
								<?php if (isset($url)): ?>
									</a>
								<?php endif; ?>
							<?php endif; ?>

						<?php elseif ($bnType == 3) : ?>
							<?php if (!$buttonText): ?>
								<?php if ($url): ?>
									<a href="<?= $url; ?>" target="<?= $target; ?>" >
								<?php endif; ?>
							<?php endif; ?>
								<span class="banner-custom"><?= dfa($bn, 'custom') ?></span>
							<?php if (!$buttonText): ?>
								<?php if ($url): ?>
									</a>
								<?php endif; ?>
							<?php endif; ?>
						<?php elseif ($bnType == 2) : ?>
							<span class="banner-video">
								<?= $b->getVideoHtml(dfa($bn, 'video')) ?>
							</span>
						<?php endif; ?>
						<div class="content_slider">
							<?php if (dfa($bn, 'show_title') && ($title = dfa($bn, 'title'))) { ?>
								<span class="banner-title"><?= $title; ?></span>
							<?php } ?>
							<?php if (
								($showDescription = dfa($bn, 'show_description'))
								&& ($description = dfa($bn, 'description'))) { ?>
								<span class="banner-description"><?= $description; ?></span>
							<?php } ?>
							<div class="buttons">
								<?php
								if ($customCss = dfa($bn, 'custom_css')) { /** @var string $customCss */?>
									<style scoped><?= $customCss; ?></style>
								<?php } ?>
								<?php if ($buttonText && $url) { ?>
									<a class="action primary" href="<?= $url; ?>" target="<?= $target; ?>"
										<?php if($isGatEnabled):?>
											data-track-promo-id="<?= $gaPromoId; ?>"
											data-track-promo-name="<?= $gaPromoName; ?>"
											data-track-promo-creative="<?= $gaPromoCreative; ?>"
											data-track-promo-position="<?= $gaPromoPosition; ?>"
										<?php endif;?>
									>
										<?= $buttonText; ?>
									</a>
								<?php }
								if ($customContent = dfa($bn, 'custom_content')) { ?>
									<div class="clearfix"></div>
									<div class="custom_content"><?= $customContent; ?></div>
								<?php } ?>
							</div>
						</div>
					</div>
			<?php } ?>
		</div>
		<div id="pre-div">
			<div class="cssload-loader">
				<div class="cssload-inner cssload-one"></div>
				<div class="cssload-inner cssload-two"></div>
				<div class="cssload-inner cssload-three"></div>
			</div>
		</div>
	</div>
	<script>
		require(['jquery', 'owl_carousel', 'owl_config' ],
			function ($) {
				$(document).ready(function() {

					var slider_id = <?= $sliderId; ?>;
					var slider_config = <?= $cfg; ?>;

					var items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 1);
					if(slider_config.transition != 'slide') {
						items = 1;
					}

					var stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0;
					var animate_Out = slider_config.transition != 'fadeOut' ? true : false;

					/** Lazyload bug when fewer items exist in the carousel then the ones displayed */
					$('.owl-carousel-custom-'+slider_id).on('initialized.owl.carousel', function(event){
						var scopeSize = event.page.size;
						for (var i = 0; i < scopeSize; i++){
							var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
							$(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
							$(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
						}
					});

					$('.owl-carousel-custom-'+slider_id).owlCarousel({
						nav               :parseInt(slider_config.nav) == 1 ? true : false,
						dots              :parseInt(slider_config.dots) == 1 ? true : false,
						center            :(slider_config.center == 1 && animate_Out) ? true : false,
						items             :items,
						loop              :parseInt(slider_config.loop) == 1 ? true : false,
						margin            :(slider_config.margin != '' && animate_Out) ? parseInt(slider_config.margin) : 0,
						stagePadding      :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
						lazyLoad          :parseInt(slider_config.lazyLoad) == 1 ? true : false,
						autoplay          :parseInt(slider_config.autoplay) == 1 ? true : false,
						autoplayTimeout   :(parseInt(slider_config.autoplayTimeout) > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
						autoplayHoverPause:parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
						autoHeight        :parseInt(slider_config.autoHeight) == 1 ? true : false,
						animateOut        :slider_config.transition == 'slide' ? false : slider_config.transition,


						responsive:{
							<?= $breakpoint['breakpoint_1']; ?>:{
								nav     :parseInt(slider_config.nav_brk1) == 1 ? true : false,
								items   :parseInt(slider_config.items_brk1  >= 0 ? slider_config.items_brk1 : 0),
							},
							<?= $breakpoint['breakpoint_2']; ?>:{
								nav     :parseInt(slider_config.nav_brk2) == 1 ? true : false,
								items   :parseInt(slider_config.items_brk2  >= 0 ? slider_config.items_brk2 : 0),
							},
							<?= $breakpoint['breakpoint_3']; ?>:{
								nav     :parseInt(slider_config.nav_brk3) == 1 ? true : false,
								items   :parseInt(slider_config.items_brk3  >= 0 ? slider_config.items_brk3 : 0),
							},
							<?= $breakpoint['breakpoint_4']; ?>:{
								nav     :parseInt(slider_config.nav_brk4) == 1 ? true : false,
								items   :parseInt(slider_config.items_brk4  >= 0 ? slider_config.items_brk4 : 0),
							}
						}
					});

					$('.owl-carousel-custom-'+slider_id).on('resized.owl.carousel', function (event) {
						var $that = $(this);
						setTimeout(function(){
							$that.find('.owl-height').css('height', $that.find('.owl-item.active').height());
						}, 100);
					});

					setTimeout(function(){
						var $that = $('.owl-carousel-custom-'+slider_id);
						$that.find('.owl-height').css('height', $that.find('.owl-item.active').height());
					}, 100);

				});
			});
	</script>
<?php }