<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<?php /** @var \Amasty\MegaMenu\Block\Head $block */
if ($block->isModuleEnabled()) :?>
    <style>
        .ammenu-nav-sections.-hamburger,
        .ammenu-menu-wrapper.-desktop,
        .ammenu-menu-wrapper.-hamburger-top,
        .ammenu-nav-sections .ammenu-title,
        .ammenu-main-container .ambrands-popup-filter {
            background: <?= $block->escapeHtml($block->getColorStyle('menu_background'))?> !important;
        }

        .ammenu-menu-wrapper.-desktop .ammenu-item.-main > .ammenu-link,
        .ammenu-menu-wrapper.-hamburger-top .ammenu-item.-main .ammenu-link,
        .ammenu-nav-sections .ammenu-title > .ammenu-link {
            color: <?= $block->escapeHtml($block->getColorStyle('menu_text'))?> !important;
        }

        .ammenu-menu-wrapper.-desktop .ammenu-submenu-container .ammenu-link,
        .ammenu-menu-wrapper.-desktop .ammenu-submenu-container,
        .ammenu-menu-wrapper.-desktop .ammenu-product-list .product-item-info *:not(.-nocolor):not(.swatch-option),
        .ammenu-menu-wrapper.-hamburger-top .ammenu-submenu-container,
        .ammenu-nav-sections.-hamburger .ammenu-submenu-container,
        .ammenu-menu-wrapper.-mobile .ammenu-link {
            color: <?= $block->escapeHtml($block->getColorStyle('submenu_text'))?> !important;
        }

        .ammenu-nav-sections *:not(.swatch-option, .ammenu-menu-header) {
            color: <?= $block->escapeHtml($block->getColorStyle('submenu_text'))?> !important;
        }

        .ammenu-nav-sections.-hamburger .ammenu-icon:before,
        .ammenu-nav-sections.-hamburger .ammenu-icon:after,
        .ammenu-menu-wrapper.-mobile .ammenu-icon:before,
        .ammenu-menu-wrapper.-mobile .ammenu-icon:after {
            background-color: <?= $block->escapeHtml($block->getColorStyle('submenu_text'))?> !important;
        }

        .ammenu-submenu-container[aria-selected="true"] ~ .ammenu-toggle .ammenu-icon:after,
        .ammenu-submenu-container[aria-selected="true"] ~ .ammenu-toggle .ammenu-icon:before {
            background-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
        }

        .ammenu-menu-wrapper.-desktop .ammenu-item.-main:hover > .ammenu-link,
        .ammenu-submenu-container[aria-selected="true"] ~ .ammenu-link {
            color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
        }

        .ammenu-items .current,
        .ammenu-items .current > .ammenu-wrapper {
            background-color: <?= $block->escapeHtml($block->getColorStyle('menu_highlight'))?>;
        }

        .ammenu-menu-wrapper.-desktop .ammenu-submenu-container,
        .ammenu-menu-wrapper.-desktop.ammenu-item.-main:hover,
        .ammenu-menu-wrapper.-desktop .ammenu-link:not(.-level1) + .ammenu-item.-child,
        .ammenu-menu-wrapper.-hamburger-top .ammenu-submenu-container,
        .ammenu-nav-sections.-hamburger .ammenu-submenu-container,
        .ammenu-nav-sections .ammenu-title.active,
        .ammenu-nav-sections .ammenu-content,
        .ammenu-menu-wrapper.-mobile .ammenu-submenu,
        .ammenu-menu-wrapper.-mobile .ammenu-link.-main,
        .ammenu-main-container .brand-images .brands-letter .letter .title {
            background: <?= $block->escapeHtml($block->getColorStyle('submenu_background'))?> !important;
        }

        .ammenu-main-container .ambrands-list-popup {
            background: <?= $block->colourBrightness($block->escapeHtml($block->getColorStyle('submenu_background')), .9)?> !important;
        }

        .ammenu-main-container .ambrands-popup-filter .ambrands-letter.-disabled {
            background: <?= $block->colourBrightness($block->escapeHtml($block->getColorStyle('submenu_background')), .8)?> !important;
        }

        .ammenu-menu-wrapper.-desktop .ammenu-link:hover > .ammenu-wrapper,
        .ammenu-menu-wrapper.-desktop .ammenu-link.-hovered > .ammenu-wrapper,
        .ammenu-menu-wrapper.-mobile .ammenu-link.-level2:hover,
        .ammenu-menu-wrapper.-hamburger-top .ammenu-item:hover .ammenu-link,
        .ammenu-item:hover > .ammenu-link,
        .ammenu-nav-sections.-hamburger .ammenu-link:hover .ammenu-wrapper {
            color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
        }

        .ammenu-menu-welcome,
        .ammenu-menu-wrapper.-desktop .ammenu-main-container .ammenu-link.-level1:hover:before,
        .ammenu-menu-wrapper.-desktop .ammenu-categories-container .ammenu-arrow,
        .ammenu-menu-wrapper.-desktop .ammenu-categories-container .ammenu-arrow:before,
        .ammenu-menu-wrapper.-desktop .ammenu-categories-container .ammenu-arrow:after {
            background: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
            border-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
        }

        .ammenu-menu-wrapper.-hamburger .ammenu-wrapper a:hover {
            border-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
        }

        .ammenu-menu-toggle .ammenu-icon {
            border-color: <?= $block->escapeHtml($block->getColorStyle('toggle_icon_color'))?> !important;
        }

        .ammenu-menu-close-btn {
            color: <?= $block->escapeHtml($block->getColorStyle('toggle_icon_color'))?> !important;
        }

        .ammenu-nav-sections.-hamburger .ammenu-menu-welcome .message{
            color: <?= $block->escapeHtml($block->getColorStyle('menu_background'))?> !important;
        }
    </style>
<?php endif; ?>
