<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>

<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="ammenu-nav-sections nav-sections<?= $block->getHelperBlock()->isHamburgerEnabled() ? ' -hamburger' : '' ?>" data-ammenu-js="nav-sections">
        <?php $layout = $block->getLayout(); ?>
        <div class="ammenu-tabs-container" data-mage-init='<?= /* @escapeNotVerified */ $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <?php if (!$block->getHelperBlock()->isHamburgerEnabled()) :?>
                    <div class="ammenu-title" data-role="collapsible">
                        <a class="ammenu-link" title="<?= $label ?>" data-toggle="switch" href="#<?= /* @escapeNotVerified */ $alias ?>"><?= /* @escapeNotVerified */ $label ?></a>
                    </div>
                    <div class="ammenu-content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content"><?= /* @escapeNotVerified */ $html ?></div>
                <?php endif; ?>
                <?php if ($block->getHelperBlock()->isHamburgerEnabled()) :?>
                    <div id="<?= /* @escapeNotVerified */ $alias ?>" ><?= /* @escapeNotVerified */ $html ?></div>
                <?php endif; ?>
            <?php endforeach;?>
        </div>
    </div>
    <div class="ammenu-menu-overlay" data-ammenu-js="menu-overlay"></div>
<?php endif; ?>
