<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<span data-ammenu-js="menu-toggle"
      class="ammenu-menu-toggle<?= /* @noEscape */ $block->isHamburgerEnabled() ? ' -hamburger' : '' ?><?= /* @noEscape */ $block->getData('is_porto') ? ' -porto' : '' ?>"
>
    <span class="ammenu-icon"></span>
    <span class="ammenu-icon"></span>
    <span class="ammenu-icon"></span>
</span>
