<?php
/**
 * @category  Trustedshops
 * @package   Trustedshops\Trustedshops
 * @author    Trusted Shops GmbH
 * @copyright 2016 Trusted Shops GmbH
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.trustedshops.de/
 */
?>
<?php /** @var Trustedshops\Trustedshops\Block\Rating\Tab $this */ ?>
<?php
/**
 * content element for trustedshops rating
 */
?>
<div id='ts_product_widget'></div>
