<?php
/**
 * Copyright © 2015 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php $items = $block->getCollection(); ?>

<?php if (!empty($items)): ?>
<h3><?php echo __('Pages') ?></h3>
<ul class="pages">
<?php foreach ($items as $item): ?>
<li class="page-url">
    <a href="<?php echo $block->escapeUrl($item->getUrl()) ?>"><?php echo $block->escapeHtml($item->getTitle()) ?></a>
</li>
<?php endforeach; ?>
</ul>
<?php endif;