<?php
/**
 * Copyright © 2015 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php $stores = $block->getStores(); ?>
<?php if (count($stores)): ?>
<h3><?php echo __('Stores') ?></h3>
<ul class="stores">
    <?php foreach ($stores as $store): ?>
    <li class="store">
        <?php if ($block->getCurrentStoreId() == $store->getId()): ?>
            <?php echo $block->escapeHtml($store->getName()) ?>
        <?php else: ?>
            <a href="#" data-post='<?= $block->getTargetStorePostData($store) ?>'>
                <?php echo $block->escapeHtml($store->getName()) ?>
            </a>
        <?php endif ?>
    </li>
    <?php endforeach ?>
</ul>
<?php endif ?>