<?php

$_element = $block->getElement();
$_note    = $_element->getNote();
$_trId    = $_element->getHtmlContainerId();
$_class   = $_element->getFieldsetHtmlClass();
?>
<?php if (!$_element->getNoDisplay()): ?>
<div<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
    <?php if ($_element->getType()=='hidden'): ?>
         <div class="hidden"><?php echo trim($_element->getElementHtml()) ?></div>
    <?php else: ?>
         <div class="hor-scroll">
            <p class="label<?php echo $_class ? " {$_class}-label" : ''?>" style="font-weight:bold; padding-left: 5px;"><?php echo trim($_element->getLabelHtml()) ?></p>
            <?php if ($_note): ?>
               <p class="note<?php echo $_class ? " {$_class}-note" : ''?>" id="note_<?php echo $_element->getId()?>"><span><?php echo $_note ?></span></p>
            <?php endif ?>
            <div class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>">
                <?php echo trim($_element->getElementHtml()) ?>
           </div>
       </div>
    <?php endif; ?>
</div>
<?php endif; ?>
