<?php
$_productCollection = [];
$helper = $this->helper("Ves\Megamenu\Helper\Data");
$imgHelper = $this->helper("Ves\Megamenu\Helper\Image");
if ($exist = ($collection = $block->getProductCollection() && $block->getProductCollection()->getSize())) {
	$type = 'widget-new-grid';
	$mode = 'grid';
	$image = 'new_products_content_widget_grid';
	$title = $this->getConfig("widget_title");
	$items = $block->getProductCollection()->getItems();

	$productCollection = $block->getProductCollection();
	$number_item_percolumn = (int)$this->getConfig("number_item_percolumn", 1);
	$total = $productCollection->count();
	if($total%$number_item_percolumn == 0){
		$column = $total/$number_item_percolumn;
	}else{
		$column = floor($total/$number_item_percolumn)+1;
	}

	//if($column<$this->getConfig("column")) $column = $large_max_items;
	$i = $x = 0;
	foreach ($productCollection as $_product) {
		if($i<$column){
			$i++;
		}else{
			$i = 1;
			$x++;
		}
		$_productCollection[$i][$x] = $_product;
	}

	$showWishlist    = $this->getConfig("show_wishlist");
	$showCompare     = $this->getConfig("show_compare");
	$showCart        = $this->getConfig("show_addtocart");
	$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$description     = $this->getConfig("show_short_description");
	$show_name       = $this->getConfig("show_name");
	$show_price      = $this->getConfig("show_price");
	$show_review     = $this->getConfig("show_review");
	$show_image      = $this->getConfig("show_image");
	$show_new_label  = $this->getConfig("show_new_label");
	$show_sale_label = $this->getConfig("show_sale_label");
	$image_width     = $this->getConfig('image_width',150);
	$image_height    = (int)$this->getConfig('image_height');
	$item_height     = (int)$this->getConfig('item_height');

	//If image width is not specified, use default values
	if ($image_width <= 0){
		$image_width = 150;
		$image_height = 150;
	}
	$catViewKeepFrame = TRUE;

	if ($helper->getCoreRegistry()->registry('catViewKeepFrame') === NULL){
		$helper->getCoreRegistry()->register('catViewKeepFrame', $catViewKeepFrame);
	}
}
$large_max_items    = (int)$this->getConfig('large_max_items',6);
$large_items        = (int)$this->getConfig('large_items',5);
$portrait_items     = (int)$this->getConfig('portrait_items',4);
$tablet_items       = (int)$this->getConfig('tablet_items',4);
$tablet_small_items = (int)$this->getConfig('tablet_small_items',2);
$mobile_items       = (int)$this->getConfig('mobile_items',1);
$blockId            = time().rand();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$short_max_char     = (int)$this->getConfig('short_max_char',100);
$show_learnmore     = $this->getConfig('show_learnmore');
$block_width        = (int)$this->getConfig('block_width');
?>
<?php if ($exist): ?>
	<div class="block widget megamenu-widget products-widget">
		<?php if($title!=''){ ?>
		<div class="block-title">
			<strong><?php echo $title; ?></strong>
		</div>
		<?php } ?>
		<div class="block-content">
			<?php if($this->getConfig("nav") && count($_productCollection)>0){ ?>
			<div class="owl-nav">
				<a href="javascript:void(0)" data-owlid="menuowl-<?php echo $blockId ?>" class="owl-left"><i class="fa fa-angle-left"></i></a>
				<a href="javascript:void(0)" data-owlid="menuowl-<?php echo $blockId ?>" class="owl-right"><i class="fa fa-angle-right"></i></a>
			</div>
			<?php } ?>
			<div class="products-grid grid megamenuowl-play">
				<ol id="menuowl-<?php echo $blockId ?>" class="product-items owl-carousel <?php echo $type; ?> megamenu-products<?php echo $blockId ?>"
					data-items="<?php echo $this->getConfig("column", 3); ?>"
					data-mousedrag="<?php echo $this->getConfig("mousedrag")?"true":"false"; ?>"
					data-pulldrag="<?php echo $this->getConfig("pulldrag")?"true":"false"; ?>"
					data-freedrag="<?php echo $this->getConfig("freedrag")?"true":"false"; ?>"
					data-stagepadding="<?php echo (int)$this->getConfig("stagepadding") ?>"
					data-lazyload="<?php echo $this->getConfig("lazyload")?"true":"false"; ?>"
					data-rtl="<?php echo $this->getConfig("rtl")?"true":"false"; ?>"
					data-center="<?php echo $this->getConfig("center")?"true":"false"; ?>"
					data-margin="<?php echo (int)$this->getConfig("margin") ?>"
					data-autoplay="<?php echo $this->getConfig("autoplay")?"true":"false"; ?>"
					autoplay-timeout="<?php echo $this->getConfig("autoplay_timeout", 3000); ?>"
					data-dot="<?php echo $this->getConfig("dots")?"true":"false"; ?>"
					data-loop="<?php echo $this->getConfig("loop")?"true":"false"; ?>"
					data-nav = "false"
					data-autoplay-pauonhover="<?php echo $this->getConfig("autoplay_hoverpause")?"true":"false"; ?>"
					data-mobile-items="<?php echo $mobile_items; ?>"
					data-tablet-small-items="<?php echo $tablet_small_items; ?>"
					data-tablet-items="<?php echo $tablet_small_items; ?>"
					data-portrait-items="<?php echo $portrait_items; ?>"
					data-large-items="<?php echo $large_items; ?>"
					data-large-max-items="<?php echo $large_max_items; ?>"
					<?php if($block_width){ ?>style="width: <?php echo $block_width; ?>px !important"<?php } ?>>
						<?php $iterator = 1; ?>
						<?php foreach ($_productCollection as $_columnCollection) { ?>
						<?php echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
						<?php foreach ($_columnCollection as $_item): ?>
							<div class="product-block" <?php if($item_height){ echo "style='height:".$item_height."px;max-width: 100%;'"; } ?>>
								<div class="product-item-info">
									<?php if($show_new_label || $show_sale_label){ ?>
									<div class="icon">
										<?php
										if($show_sale_label) {
											$specialprice = $_item->getSpecialPrice();
											$specialPriceFromDate = $_item->getSpecialFromDate();
											$specialPriceToDate = $_item->getSpecialToDate();
											$today =  time();
											if ($specialprice) {
												if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
													?>
													<span class="onsale"><?php echo __("Sale");?></span>
													<?php
												}
											}
										}
										if($show_new_label) {
											$is_new = $block->checkProductIsNew( $_item );
											if($is_new) { ?>
											<span class="new-icon"><?php echo __("New");?></span>
											<?php
										}
									}
									?>
								</div>
								<?php } ?>
								<?php if($show_image){ ?>
								<?php $_image = $imgHelper->getImg($_item, $image_width, $image_height, 'category_page_grid'); ?>
								<?php if($_image){ ?>
								<div class="product-image">
									<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
										<img src="<?php echo $_image->getUrl(); ?>" alt="<?php echo $_image->getLabel() ?>" />
									</a>
									<?php if ($showWishlist || $showCompare || $showCart): ?>
										<div class="product-item-actions">
											<?php if ($showCart): ?>
												<div class="actions-primary">
													<?php if ($_item->isSaleable()): ?>
														<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
															<button class="action tocart primary"
															data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
															type="button" title="<?php echo __('Add to Cart') ?>">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php
														$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="action tocart primary"
														data-post='<?php echo $postData; ?>'
														type="button" title="<?php echo __('Add to Cart') ?>">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
												<?php endif; ?>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
									<?php if ($showWishlist || $showCompare): ?>
										<div class="actions-secondary" data-role="add-to-links">
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
												<a href="#"
												data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
												class="action towishlist" data-action="add-to-wishlist"
												title="<?php echo __('Add to Wish List') ?>">
												<span><?php echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
										<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
											<a href="#" class="action tocompare"
											data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
											title="<?php echo __('Add to Compare') ?>">
											<span><?php echo __('Add to Compare') ?></span>
										</a>
									<?php endif; ?>
								</div>
							<?php endif; ?>
						</div>
					<?php endif; ?>
				</div>
				<?php } ?>
				<?php } ?>
				<div class="product-item-details">
					<?php if($show_name){ ?>
					<strong class="product-item-name">
						<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
							href="<?php echo $block->getProductUrl($_item) ?>"
							class="product-item-link">
							<?php echo $block->escapeHtml($_item->getName()) ?>
						</a>
					</strong>
					<?php } ?>

					<?php // Short Description ?>
					<?php $shortDescription = $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description'); ?>
					<?php if ($description && $shortDescription){ ?>
					<div class="product-item-inner">
						<div class="product-item-description">
							<?php $short_description = $helper->subString($shortDescription, $short_max_char, '...'); ?>
							<?php echo $short_description; ?>
							<?php if($show_learnmore && $shortDescription!=''){ ?>
							<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="action more">
								<?php echo __('Learn More') ?>
							</a>
							<?php } ?>
						</div>
					</div>
					<?php } ?>

					<?php // Price ?>
					<?php if($show_price){ ?>
					<?php echo $block->getProductPrice($_item) ?>
					<?php } ?>
					<?php if ($show_review && $templateType): ?>
						<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
					<?php endif; ?>
				</div>
			</div>
		</div>
	<?php endforeach ?>
	<?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
	<?php } ?>
</ol>
</div>
</div>
</div>
<?php endif; ?>