<?php
$_productCollection = [];
$helper = $this->helper("Ves\Megamenu\Helper\Data");
$collection = [];
$exit = [];
$imgHelper = $this->helper("Ves\Megamenu\Helper\Image");
if ($exit = ($collection = $block->getProductCollection() && $block->getProductCollection()->getSize())) {
	$type = 'widget-new-grid';
	$mode = 'grid';
	$image = 'new_products_content_widget_grid';
	$title = $this->getConfig("widget_title");
	$collection = $block->getProductCollection();

	$showWishlist    = $this->getConfig("show_wishlist");
	$showCompare     = $this->getConfig("show_compare");
	$showCart        = $this->getConfig("show_addtocart");
	$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$description     = $this->getConfig("show_short_description");
	$show_name       = $this->getConfig("show_name");
	$show_price      = $this->getConfig("show_price");
	$show_review     = $this->getConfig("show_review");
	$show_image      = $this->getConfig("show_image");
	$show_new_label  = $this->getConfig("show_new_label");
	$show_sale_label = $this->getConfig("show_sale_label");
	$image_width     = $this->getConfig('image_width',150);
	$image_height    = $this->getConfig('image_height');

	//If image width is not specified, use default values
	if ($image_width <= 0){
		$image_width = 150;
		$image_height = 150;
	}
	$catViewKeepFrame = TRUE;

	if ($helper->getCoreRegistry()->registry('catViewKeepFrame') === NULL){
		$helper->getCoreRegistry()->register('catViewKeepFrame', $catViewKeepFrame);
	}
	$column = $this->getConfig('large_items', 4);
	$xs = 12/$column;
}
$blockId = time().rand();
?>
<?php if ($exit): ?>
	<?php $total = $collection->count(); ?>
	<div class="megamenu-widget products-widget">
		<?php if($title!=''){ ?>
		<div class="block-title">
			<strong role="heading" aria-level="2"><?php echo $title; ?></strong>
		</div>
		<?php } ?>
		<div class="block-content">
			<?php $x = 0; ?>
			<div class="product-items <?php echo $type; ?> megamenu-products<?php echo $blockId ?>">
				<?php $iterator = 1; ?>
				<?php foreach ($collection as $_item) { ?>
				
				<?php if( $column == 1 || $x%$column == 0){ ?>
				<div class="row">
					<?php } ?>
					<div class="product-item col-lg-<?php echo $xs; ?> col-md-3 col-sm-4 col-xs-6">
						<div class="product-item-info">
							<?php // Sale Icon, New Icon Block ?>
							<?php if($show_new_label || $show_sale_label){ ?>
							<div class="icon">
								<?php
								if($show_sale_label) {
									$specialprice = $_item->getSpecialPrice();
									$specialPriceFromDate = $_item->getSpecialFromDate();
									$specialPriceToDate = $_item->getSpecialToDate();
									$today =  time();
									if ($specialprice) {
										if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
											?>
											<span class="onsale"><?php echo __("Sale");?></span>
											<?php
										}
									}
								}
								if($show_new_label) {
									$is_new = $block->checkProductIsNew( $_item );
									if($is_new) { ?>
									<span class="new-icon"><?php echo __("New");?></span>
									<?php
								}
							}
							?>
						</div>
						<?php } ?>

						<?php if($show_image){ ?>
						<?php $_image = $imgHelper->getImg($_item, $image_width, $image_height, 'category_page_grid'); ?>
						<?php if($_image){ ?>
						<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
							<img src="<?php echo $_image->getUrl(); ?>" alt="<?php echo $_image->getLabel() ?>" />
						</a>
						<?php } ?>
						<?php } ?>

						<div class="product-item-details">
							<?php if($show_name){ ?>
							<strong class="product-item-name">
								<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
									href="<?php echo $block->getProductUrl($_item) ?>"
									class="product-item-link">
									<?php echo $block->escapeHtml($_item->getName()) ?>
								</a>
							</strong>
							<?php } ?>

							<?php // Price ?>
							<?php if($show_price){ ?>
							<?php echo $block->getProductPrice($_item) ?>
							<?php } ?>

							<?php if ($show_review && $templateType): ?>
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
							<?php endif; ?>

							<?php if ($showWishlist || $showCompare || $showCart): ?>
								<div class="product-item-actions">
									<?php if ($showCart): ?>
										<div class="actions-primary">
											<?php if ($_item->isSaleable()): ?>
												<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
													<button class="action tocart primary"
													data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
													type="button" title="<?php echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php
												$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												?>
												<button class="action tocart primary"
												data-post='<?php echo $postData; ?>'
												type="button" title="<?php echo __('Add to Cart') ?>">
												<span><?php echo __('Add to Cart') ?></span>
											</button>
										<?php endif; ?>
									<?php else: ?>
										<?php if ($_item->getIsSalable()): ?>
											<div class="stock available"><span><?php echo __('In stock') ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
							<?php endif; ?>
							<?php if ($showWishlist || $showCompare): ?>
								<div class="actions-secondary" data-role="add-to-links">
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
										<a href="#"
										data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
										class="action towishlist" data-action="add-to-wishlist"
										title="<?php echo __('Add to Wish List') ?>">
										<span><?php echo __('Add to Wish List') ?></span>
									</a>
								<?php endif; ?>
								<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
									<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
									<a href="#" class="action tocompare"
									data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
									title="<?php echo __('Add to Compare') ?>">
									<span><?php echo __('Add to Compare') ?></span>
								</a>
							<?php endif; ?>
						</div>
					<?php endif; ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
</div>

<?php if( $column == 1 || ($x+1)%$column == 0 || $x == ($total-1) ) {  ?>
</div><!-- ROW -->
<?php } ?>
<?php $x++; ?>
<?php } ?>
</div>
</div>
</div>
<?php endif; ?>