<?php
# 2020-10-28 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Improve the frontend header's finance banner": https://github.com/tradefurniturecompany/site/issues/201
?>
<p>
	<a href="/finance-available">12 MONTHS <span class="highlight">0% FINANCE</span> AVAILABLE</a>
	<a href="/wood-samples">
		<span class="highlight">Wood Samples Available</span>
		<img src='<?= df_media_path2url('wysiwyg/wood_samples.png') ?>' alt='wood samples'/>
	</a>
</p>