<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<li class="authorization-link <?php if($block->isLoggedIn()){ echo "logout";} else { echo "login";}?>" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?> title="<?php if($block->isLoggedIn()){ echo "logout";} else { echo "login";}?>">
      <span><?php echo $block->escapeHtml($block->getLabel()) ?></span>
    </a>
</li>
