<?php /** @var $block \IWD\InfinityScroll\Block\Frontend\Init */ ?>

<?php if ($block->isEnabled()) : ?>

    <?php if ($block->getCurPage() > 1) : ?>
    <div id="iwd-loaded-pages-top">
        <div id="iwd-load-prev-page"><?php echo $block->getLoadPrevPageButtonLabel(); ?></div>
        <div class="iwd-load-bar top-bar"></div>
        <div class="iwd-uploaded-pages"></div>
    </div>
    <?php endif; ?>

    <div id="iwd-loaded-pages">
        <div class="iwd-uploaded-pages"></div>
        <?php if ($block->isButtonMode() && $block->getCountPages() > $block->getCurPage()) : ?>
            <div id="iwd-load-next-page"><?php echo $block->getLoadNextPageButtonLabel(); ?></div>
        <?php endif; ?>
        <div class="iwd-load-bar bottom-bar"></div>
    </div>

    <script>
        require([
            'jquery',
            'IWD_InfinityScroll/js/infinity.scroll'
        ], function ($, iwdInfinityScroll) {
            $( document ).ready(function () {
                var infinityScroll = new iwdInfinityScroll();
                infinityScroll.init(<?php echo $block->getOptionsJson() ?>);
            });
        });
    </script>
    <?php if (!$block->isPagination()) : ?>
    <style>
        <?php echo $this->getXpathSelectorLimiter() . ', '
            . $this->getXpathSelectorPagination() . ', '
            . $this->getXpathSelectorAmount() ?> {display:none;}
    </style>
    <?php endif; ?>
<?php endif; ?>