<?php if ($block->getForms()): ?>
    <div id="<?php echo $block->getId() ?>" class="config-nav">
    	<div class="config-nav-block admin__page-nav">
                <div class="admin__page-nav-title title" data-role="title">
                    <strong>Realex</strong>
                </div>

                <ul class="admin__page-nav-items items" data-role="content">
                    <?php $_iterator = 1; ?>
                    <?php
                    foreach ($block->getForms() as $_form) : ?>
                        <li class="admin__page-nav-item item
                        	<?php if ($block->isFormActive($_form)): ?> _active<?php endif ?>">
                            <a href="<?php echo $block->getFormUrl($_form) ?>"
                               class="admin__page-nav-link item-nav">
                               <span><?php echo $_form->getTitle() ?></span>
                            </a>
                        </li>
                        <?php $_iterator++; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
    </div>
<?php endif; ?>